[package]
name = "data_management"
version = "0.1.0"
authors = ["umut ucok <ucok.umut@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.3"
lego_config = {path = "../lego_config"}